config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :comments, only: [:create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :text             not null
#  user_id           :integer          not null
#  post_id           :integer          not null
#  created_at        :datetime
#  updated_at        :datetime
#  parent_comment_id :integer
#

class Comment < ActiveRecord::Base
  validates :content, :user_id, :post_id, presence: true
  belongs_to :user
  belongs_to :post
  has_many(
    :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  )
  belongs_to(
    :parent_comment,
    class_name: "Comment",
    foreign_key: :parent_comment_id,
    primary_key: :id
  )
  has_many :votes, as: :votable

  def child_comments
    @comments = Comment.where(parent_comment_id: self.id)
  end

  def top_level_comments
    @comments = Comment.where(parent_comment_id: nil)
  end

  def has_child_comments?
    @comments = Comment.where(parent_comment_id: self.id)
    return false if @comments.empty?
    true
  end

  def vote_sum_votable_id
    Vote.where(votable_id: self.id).sum(:value)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new(post_id: params[:post_id])
    render :new
  end

  def create
    @comment = Comment.new(params_comment)
    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find_by_id(params[:id])
    render :show
  end

  def upvote
    @comment = Comment.find_by_id(params[:id])
    @vote = Vote.new(value: 1, votable_id: @comment.id, votable_type: "Comment")
    @vote.save
    redirect_to comment_url(@comment)
  end

  def downvote
    @comment = Comment.find_by_id(params[:id])
    @vote = Vote.new(value: -1, votable_id: @comment.id, votable_type: "Comment")
    @vote.save
    redirect_to comment_url(@comment)
  end

  private
  def params_comment
    params.require(:comment).permit(:content, :user_id, :post_id, :parent_comment_id)
  end
end

app/views/comments/_comment.html.erb
<ul>
  <% comments_by_parent_id[parent_comment.id].each do |child_comment| %>
    <li>
      (<%= child_comment.vote_sum_votable_id %>)
      <%= link_to child_comment.content, comment_url(child_comment) %>
      <%= render "comments/comment",
          parent_comment: child_comment,
          comments_by_parent_id: comments_by_parent_id %>
    </li>
  <% end %>
</ul>

app/views/comments/new.html.erb
<h1>New Comment!</h1>

<% if !flash.now[:errors].nil? %>
  <ul>
    <% flash.now[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <label for="comment_content">Content</label>
  <br>
  <textarea id="comment_content"
            name="comment[content]"
            value="<%= @comment.content %>"></textarea>
  <br>

  <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  
  <input type="submit" value="Submit">
</form>

app/views/comments/show.html.erb
<%= @comment.content %> by <%= @comment.user.email %>
<br>
<%= @comment.vote_sum_votable_id %> upvotes
<br>
<br>
<%= button_to "Upvote", upvote_comment_url(@comment) %>
<%= button_to "Downvote", downvote_comment_url(@comment) %>
<br>

<b>Reply to this comment:</b>

<% if !flash.now[:errors].nil? %>
  <ul>
    <% flash.now[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <label for="comment_content">Content</label>
  <br>
  <textarea id="comment_content"
            name="comment[content]"
            value="<%= @comment.content %>"></textarea>
  <br>

  <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <input type="hidden"
         name="comment[parent_comment_id]"
         value="<%= @comment.id %>">

  <input type="submit" value="Submit">
</form>