config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :comments, only: [:create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  moderator_id :integer          not null
#  title        :string           not null
#  description  :text             not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Sub < ActiveRecord::Base
  validates :moderator_id, :title, :description, presence: true
  
  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id
  )
  has_many :post_subs, dependent: :destroy
  has_many :posts, through: :post_subs, source: :post
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login!, only: [:new, :create]
  before_action :moderator?, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find_by_id(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find_by_id(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by_id(params[:id])
    @sub.update_attributes(sub_params)
    redirect_to sub_url(@sub)
  end

  private
  def sub_params
    params.require(:sub).permit(:moderator_id, :title, :description)
  end

  def moderator?
    @sub = Sub.find_by_id(params[:id])
    unless @sub.moderator_id == current_user.id
      flash.now[:errors] = "Only moderators allowed to edit this Sub!"
      redirect_to sub_url(@sub)
    end
  end
end

app/views/subs/_form.html.erb
<% action_url = sub_object.persisted? ? sub_url(sub_object) : subs_url %>
<% form_method = sub_object.persisted? ? "patch" : "post" %>
<% submit_button = sub_object.persisted? ? "Update" : "Create" %>

<% if !flash.now[:errors].nil? %>
  <ul>
    <% @sub.errors.full_messages do |error| %>
        <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= form_method %>">
  <%= auth_token %>

  <label for="sub_title">Title</label>
  <input type="text"
         id="sub_title"
         name="sub[title]"
         value="<%= sub_object.title %>">
  <br>
  <!-- <label for="sub_moderator">Moderator</label>
  <select id="sub_moderator"
          name="sub[moderator_id]">
          <% User.all.each do |user| %>
            <% if user.id == current_user.id %>
              <option
                  value="<%= user.id %>"
                  <%= "selected" if user.id = current_user.id %>>
                <%= user.email %>
              </option>
            <% end %>
          <% end %>
  </select> -->
  <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">

  <label for="sub_description">Description</label><br>
  <textarea id="sub_description" name="sub[description]"><%= sub_object.description %></textarea>
  <br>
  <input type="submit" value="<%= submit_button %>">
</form>

app/views/subs/edit.html.erb
<h1>Edit your Sub</h1>

<%= render "form", sub_object: @sub %>

app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<ul>
  <% Sub.all.each do |subb| %>
    <li><%= link_to subb.title, sub_url(subb) %></li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create a new sub!</h1>

<%= render "form", sub_object: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<p><b>By: <%= @sub.moderator.email %></b></p>
<b>Description</b>
<p><%= @sub.description %></p>

<% if current_user.id == @sub.moderator_id %>
  <%= link_to "Edit", edit_sub_url %>
<% end %>
<%= link_to "Make New Post", new_post_url %>

<p>
  <b>Posts:</b>
  <br>
  <ul>
    <% @sub.posts.each do |post| %>
      <li>(<%= post.vote_sum_votable_id %>) <%= link_to post.title, post_url(post) %>
      </li>
    <% end %>
  </ul>
</p>