config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    member do
      post 'upvote'
      post 'downvote'
    end
  end
  resources :comments, only: [:create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id      :integer          not null, primary key
#  title   :string(255)      not null
#  url     :string(255)
#  content :text
#  user_id :integer          not null
#

class Post < ActiveRecord::Base
  validates :title, :user_id, presence: true
  belongs_to :user
  has_many :post_subs, dependent: :destroy
  has_many :subs, through: :post_subs, source: :sub
  has_many :comments
  has_many :votes, as: :votable

  def comments_by_parent_id
    comments_by_parent_id = Hash.new { |hash, key| hash[key] = [] }
    self.comments.includes(:user).each do |comment|
      comments_by_parent_id[comment.parent_comment_id] << comment
    end
    comments_by_parent_id
  end

  def vote_sum_votable_id
    Vote.where(votable_id: self.id).sum(:value)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login!, only: [:new, :create]
  before_action :require_author!, only: [:edit, :update]

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      params[:post][:sub_ids].each do |sub_id|
        PostSub.create!(post_id: @post.id, sub_id: sub_id)
      end
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
    render :show
  end

  def edit
    @post = Post.find_by_id(params[:id])
    render :edit
  end

  def update
    @post = Post.find_by_id(params[:id])
    @post.update_attributes(post_params)
    redirect_to post_url(@post)
  end

  def upvote
    @post = Post.find_by_id(params[:id])
    @vote = Vote.new(value: 1, votable_id: @post.id, votable_type: "Post")
    @vote.save
    redirect_to post_url(@post)
  end

  def downvote
    @post = Post.find_by_id(params[:id])
    @vote = Vote.new(value: -1, votable_id: @post.id, votable_type: "Post")
    @vote.save
    redirect_to post_url(@post)
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :user_id, :sub_id)
  end

  def require_author!
    @post = Post.find_by_id(params[:id])
    if !author?
      flash.now[:errors] = "Only authors allowed to edit this post!"
      redirect_to post_url(@post)
    end
  end

  def author?
     @post = Post.find_by_id(params[:id])
    @post.user_id == current_user.id
  end
end

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% form_method = post.persisted? ? "patch" : "post" %>
<% submit_button = post.persisted? ? "Update" : "Create" %>

<%= render "shared/errors" %>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= form_method %>">
  <%= auth_token %>

  <label for="post_title">Title:</label>
  <input type="text"
         id="post_title"
         name="post[title]"
         value="<%= @post.title %>">
  <br>

  <label for="post_url">URL:</label>
  <input type="text"
         id="post_url"
         name="post[url]"
         value="<%= @post.url %>">
  <br>

  <label for="post_content">Content:</label>
  <textarea id="post_contnet" name="post[content]"><%= @post.content %></textarea>
  <br>

  <input type="hidden" name="post[user_id]" value="<%= current_user.id %>">
  <br>

  <b>Subs:</b>
  <br>
  <!-- <input type='hidden' name="post[sub_ids][]" value=""> -->
  <% Sub.all.each do |curr_sub| %>
    <label>
      <input type="checkbox"
             name="post[sub_ids][]"
             value="<%= curr_sub.id %>"
             <%= "checked" if post.sub_ids.include?(curr_sub.id) %>>
      <%= curr_sub.title %>
    </label>
    <br>
  <% end %>

  <input type="submit" value="<%= submit_button %>">
</form>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

app/views/posts/new.html.erb
<h1>New Post!</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% sum_votes = @post.vote_sum_votable_id %>
<h1>(<%= sum_votes %>) <%= @post.title %> by <%= @post.user.email %></h1>

<p>
  <b>Content:</b>
  <br>
  <%= @post.content %>
</p>

<%= button_to "Upvote", upvote_post_url %>
<%= button_to "Downvote", downvote_post_url %>
<%= link_to "Edit", edit_post_url(@post) %>

<p>
  <b>Subs:</b>
  <br>
  <ul>
    <% @post.subs.each do |curr_sub| %>
      <li><%= link_to curr_sub.title, sub_url(curr_sub) %></li>
    <% end %>
  </ul>
</p>


<h3>Comments</h3>
<%= link_to "Comment on this post!", new_post_comment_url(@post) %>

<ul>
  <% comments_by_parent_id = @post.comments_by_parent_id %>
  <% comments_by_parent_id[nil].each do |parent_comment| %>
    <li>
      (<%= parent_comment.vote_sum_votable_id %>)
      <%= link_to parent_comment.content, comment_url(parent_comment) %>
      <%= render "comments/comment",
          parent_comment: parent_comment,
          comments_by_parent_id: comments_by_parent_id %>
    </li>
  <% end %>
</ul>